SELECT
  `impressions`,
  `placement`,
  `clicks`,
  `creative`,
  `date`,
  `placement_id`,
  `rich_media_video_completions`,
  `click_rate`,
  `KEY`,
  `package_id`,
  `total_conversions`,
  `rich_media_video_plays`,
  `package_roadblock`,
  `ad`,
  `campaign`,
  `media_cost`,
  `advertiser`,
  `site`,
  NULL AS `opens`,
  NULL AS `week`,
  NULL AS `end_date`,
  NULL AS `spend`,
  NULL AS `source_file`,
  NULL AS `sends`,
  NULL AS `pageviews`,
  NULL AS `start_date`,
  NULL AS `dma`,
  NULL AS `views`,
  NULL AS `completed_views`,
  NULL AS `package_name`,
  'new_md' AS source_table
FROM
  `giant-spoon-299605.data_model_2025.new_md`
UNION ALL
SELECT
  `impressions`,
  `placement`,
  `clicks`,
  `creative`,
  NULL AS `date`,
  NULL AS `placement_id`,
  NULL AS `rich_media_video_completions`,
  NULL AS `click_rate`,
  NULL AS `KEY`,
  NULL AS `package_id`,
  NULL AS `total_conversions`,
  NULL AS `rich_media_video_plays`,
  NULL AS `package_roadblock`,
  NULL AS `ad`,
  NULL AS `campaign`,
  NULL AS `media_cost`,
  NULL AS `advertiser`,
  NULL AS `site`,
  `opens`,
  `week`,
  `end_date`,
  `spend`,
  `source_file`,
  `sends`,
  `pageviews`,
  `start_date`,
  `dma`,
  `views`,
  `completed_views`,
  `package_name`,
  'adif_fpd_data' AS source_table
FROM
  `looker-studio-pro-452620.landing.adif_fpd_data`